################
#WolfAPI Config#
################

#Plugin message format
#Keywords
#%name% Plugin Name
#%message% Plugin Message
PluginChatFormat: '&1&l%name%> &a%message%'

#Plugin error message format
#Keywords
#%name% Plugin Name
#%message% Plugin Message
PluginErrorFormat: '&4&lError From %name%> &c%message%'

#Error messages for plugins with additional info.
#Keywords
#%name% Plugin Name
#%command% Main Plugin Command
#%info% Plugin Message (If Specified)
PluginErrorMessages:
  NoPermission: 'You do not have permission to run this command!'
  NotOnline: '&f%info% &cis not online!'
  NeverJoined: '&f%info% &chas never joined the server!'
  NotNumber: '&f%info% &cis not a number!'
  NotACommand: 'That is not an available subcommand! Please use /%command% help to see available subcommands.'
  Default: 'There has been an error from plugin %name%! Please contact your server administrators.'
  Custom: '%info%'

#Error messages for plugins without additional info.
#Keywords
#%name% Plugin Name
#%command% Main Plugin Command
PluginErrorMessagesNoInfo:
  NoPermission: 'You do not have permission to run this command!'
  NotOnline: 'That player is not online!'
  NeverJoined: 'That player has never joined the server!'
  NotNumber: 'That is not a number!'
  NotACommand: 'That is not an available subcommand! Please use /%command% help to see available subcommands.'
  Default: 'There has been an error from plugin %name%! Please contact your server administrators.'
  Custom: 'There has been an error from plugin %name%! Please contact your server administrators.'

#Strip Plugin Name Color?
StripPluginNameColor: true

#Strip Plugin Message Color
StripPluginMessageColor: false

#Plugin Menu Title Color 1
PluginMenuTitleColor1: 3

#Plugin Menu Title Color 2
PluginMenuTitleColor2: 6

#Plugin Menu Information Color
PluginMenuInfoColor: b

#Replace Plugin List Commands?
ReplacePluginCommand: true

#Enable NoteBlock Music?
EnableMusic: true

#Broadcast Song Name to BarAPI?
BarBroadcast: true

#Broadcast Song Name to TitleManager?
TitleBroadcast: true

#Enable Scoreboard?
EnableScoreboard: true

#Scoreboard Title
ScoreboardTitle: '&6Server Name'

#Scoreboard Config
#Keywords
#%players% Number of Online Players
#%staff% Number of Online Staff (Staff Defined Below)
#%song% NoteBlock Song Name
#%money% Player Balance
#Types of Text
#Text - Regular Text
#TypeWriter - TypeWriter Like Text
Scoreboard:
  Line1:
    Type: 'TypeWriter'
    Text:
      - '&bWelcome to the Server!'
      - '&aTypeWriter Text!'
  Line2:
    Text:
      - '&6Players Online'
  Line3:
    Text:
      - '&a%players%'
  Line4:
    Text:
      - '&6Staff Online'
  Line5:
    Text:
      - '&a%staff%'
  Line6:
    Text:
      - '&6Current Song'
  Line7:
    Text:
      - '&a%song%'
  Line8:
    Text:
      - '&6Your Money'
  Line9:
    Text:
      - '&a%money%'

#TypeWriter Text Settings
#Delay between each time a character is added or removed (in ticks)
CharacterChangeDelay: 5
#Delay between when all characters are added and when characters begin to be removed (in ticks)
EndDelay: 40
#Delay between when all characters are removed and when characters begin to be added (in ticks)
StartDelay: 20
#Delay between pointer flashing on or off
PointerDelay: 5
#Pointer
Pointer: '_'

#Permission Plugin Groups for Staff
StaffGroups:
  - 'helper'
  - 'helperplus'
  - 'moderator'
  - 'moderatorplus'
  - 'admin'
  - 'headadmin'
  - 'coowner'
  - 'owner'

#Broadcast Message on BarAPI (%songname% is the new song name)
BarBroadcastMessage: '§a§lNow Playing §6"§c§l%songname§6"'

#Seconds the BarAPI shows the message
BarBroadcastLength: 10

#Broadcast Message on TitleManager (%songname% is the new song name)
TitleBroadcastMessage: '§a§lNow Playing §6"§c§l%songname§6"'

#Scoreboard Update Time for Money in Ticks (20 ticks per second) (Unless WolfLeader116 Economy is Enabled)
MoneyUpdate: 1200

#Scoreboard Disable Disappear Delay
ScoreboardDelay: 30

#For Internal Use ONLY! DO NOT EDIT!
Version: 1
LastSong: 0