################
#WolfAPI Config#
################

#Plugin message format
#Keywords
#%name% Plugin Name
#%message% Plugin Message
PluginChatFormat: '&1&l%name%> &a%message%'

#Plugin error message format
#Keywords
#%name% Plugin Name
#%message% Plugin Message
PluginErrorFormat: '&4&lError From %name%> &c%message%'

#Error messages for plugins with additional info.
#Keywords
#%name% Plugin Name
#%command% Main Plugin Command
#%info% Plugin Message (If Specified)
PluginErrorMessages:
  NoPermission: 'You do not have permission to run this command!'
  NotOnline: '&f%info% &cis not online!'
  NeverJoined: '&f%info% &chas never joined the server!'
  NotNumber: '&f%info% &cis not a number!'
  NotACommand: 'That is not an available subcommand! Please use /%command% help to see available subcommands.'
  Default: 'There has been an error from plugin %name%! Please contact your server administrators.'
  Custom: '%info%'

#Error messages for plugins without additional info.
#Keywords
#%name% Plugin Name
#%command% Main Plugin Command
PluginErrorMessagesNoInfo:
  NoPermission: 'You do not have permission to run this command!'
  NotOnline: 'That player is not online!'
  NeverJoined: 'That player has never joined the server!'
  NotNumber: 'That is not a number!'
  NotACommand: 'That is not an available subcommand! Please use /%command% help to see available subcommands.'
  Default: 'There has been an error from plugin %name%! Please contact your server administrators.'
  Custom: 'There has been an error from plugin %name%! Please contact your server administrators.'

#Strip Plugin Name Color?
StripPluginNameColor: true

#Strip Plugin Message Color
StripPluginMessageColor: false

#Plugin Menu Title Color 1
PluginMenuTitleColor1: 3

#Plugin Menu Title Color 2
PluginMenuTitleColor2: 6

#Plugin Menu Information Color
PluginMenuInfoColor: b

#Replace Plugin List Commands?
ReplacePluginCommand: true

#Enable NoteBlock Music?
EnableMusic: true

#Broadcast Song Name to BarAPI?
BarBroadcast: true

#Broadcast Song Name to TitleManager?
TitleBroadcast: true

#Enable Scoreboard?
EnableScoreboard: true

#Scoreboard Title
ScoreboardTitle:
  - ''
  - '&6S'
  - '&6Se'
  - '&6Ser'
  - '&6Serv'
  - '&6Serve'
  - '&6Server'
  - '&6Server '
  - '&6Server N'
  - '&6Server Na'
  - '&6Server Nam'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Name'
  - '&6Server Nam'
  - '&6Server Na'
  - '&6Server N'
  - '&6Server '
  - '&6Server'
  - '&6Serve'
  - '&6Serv'
  - '&6Ser'
  - '&6Se'
  - '&6S'
  - ''

#Scoreboard Title Update Time (in ticks)
ScoreboardTitleUpdate: 2

#Scoreboard Config
#Keywords
#%onlineplayers% Number of Online Players
#%onlinestaff% Number of Online Staff (Staff Defined Below)
#%currentsong% NoteBlock Song Name
#%money% Player Balance
#
#IF PlaceholderAPI IS INSTALLED, PUT wolfapi_ BEFORE EACH VARIABLE NAME AND USE %vaulteco_balance% INSTEAD OF %money%
#
#Types of Text
#Text - Regular Text
#TypeWriter - TypeWriter Like Text
Scoreboard:
  Line1:
    Type: 'TypeWriter'
    UpdateDelay: 5
    EndDelay: 40
    StartDelay: 20
    PointerDelay: 5
    Pointer: '_'
    Text:
      - '&bWelcome to the Server!'
      - '&aTypeWriter Text!'
  Line2:
    Type: 'Text'
    UpdateDelay: 0
    Text:
      - '&6Players Online'
  Line3:
    Type: 'Text'
    UpdateDelay: 20
    Text:
      - '&a%onlineplayers%'
  Line4:
    Type: 'Text'
    UpdateDelay: 0
    Text:
      - '&6Staff Online'
  Line5:
    Type: 'Text'
    UpdateDelay: 20
    Text:
      - '&a%onlinestaff%'
  Line6:
    Type: 'Text'
    UpdateDelay: 0
    Text:
      - '&6Current Song'
  Line7:
    Type: 'Text'
    UpdateDelay: 20
    Text:
      - '&a%currentsong%'
  Line8:
    Type: 'Text'
    UpdateDelay: 0
    Text:
      - '&6Your Money'
  Line9:
    Type: 'Text'
    UpdateDelay: 20
    Text:
      - '&a%money%'

#Text Settings
#UpdateDelay - Delay between changing between each line or updating the line if only one line is present (in ticks)

#TypeWriter Text Settings
#UpdateDelay - Delay between each time a character is added or removed (in ticks)
#EndDelay - Delay between when all characters are added and when characters begin to be removed (in ticks)
#StartDelay - Delay between when all characters are removed and when characters begin to be added (in ticks)
#PointerDelay - Delay between pointer flashing on or off (For best effect, pointer delay should be a multiple of update delay!)
#Pointer - Pointer at end of string

#Permission Plugin Groups for Staff
StaffGroups:
  - 'helper'
  - 'helperplus'
  - 'moderator'
  - 'moderatorplus'
  - 'admin'
  - 'headadmin'
  - 'coowner'
  - 'owner'

#Broadcast Message on BarAPI (%songname% is the new song name)
BarBroadcastMessage: '§a§lNow Playing §6"§c§l%songname§6"'

#Seconds the BarAPI shows the message
BarBroadcastLength: 10

#Broadcast Message on TitleManager (%songname% is the new song name)
TitleBroadcastMessage: '§a§lNow Playing §6"§c§l%songname§6"'

#Scoreboard Disable Disappear Delay
ScoreboardDelay: 30

#For Internal Use ONLY! DO NOT EDIT!
Version: 1
LastSong: 0